// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;

namespace Prenatal_MLapi
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Heart")]
            public float Heart { get; set; }

            [ColumnName(@"Movement")]
            public bool Movement { get; set; }

            [ColumnName(@"Nuchal")]
            public bool Nuchal { get; set; }

            [ColumnName(@"Anomaly")]
            public bool Anomaly { get; set; }

            [ColumnName(@"Note")]
            public string Note { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public bool Prediction { get; set; }

            public float Score { get; set; }

            // The probability calculated by calibrating the score of having true as the label.
            public float Probability { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
